/**
 * build-manual.js
 *
 * manual_template.md의 INCLUDE 플레이스홀더를 실제 파일 내용으로 교체하여
 * PROJECT_SAL_GRID_MANUAL.md를 생성합니다.
 *
 * 사용법:
 *   node build-manual.js
 *
 * 플레이스홀더 형식:
 *   <!-- INCLUDE: path/to/file.md -->
 *
 * 경로는 프로젝트 루트 기준 상대 경로입니다.
 * 예: <!-- INCLUDE: .claude/rules/01_file-naming.md -->
 */

const fs = require('fs');
const path = require('path');

// 프로젝트 루트 경로 (S0_Project-SAL-Grid_생성/manual에서 2단계 위)
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

// 파일 경로
const TEMPLATE_PATH = path.join(__dirname, 'manual_template.md');
const OUTPUT_PATH = path.join(__dirname, 'PROJECT_SAL_GRID_MANUAL.md');

// INCLUDE 패턴: <!-- INCLUDE: path/to/file.md -->
const INCLUDE_PATTERN = /<!-- INCLUDE: (.+?) -->/g;

/**
 * INCLUDE 플레이스홀더를 처리하여 파일 내용으로 교체
 */
function processIncludes(content) {
    let processed = content;
    let match;
    const errors = [];

    // 모든 INCLUDE 플레이스홀더 찾기
    while ((match = INCLUDE_PATTERN.exec(content)) !== null) {
        const placeholder = match[0];
        const relativePath = match[1].trim();
        const absolutePath = path.join(PROJECT_ROOT, relativePath);

        try {
            if (fs.existsSync(absolutePath)) {
                const fileContent = fs.readFileSync(absolutePath, 'utf-8');

                // 헤더 제거 옵션 (파일 시작이 # 으로 시작하면 첫 줄 제거)
                // 이렇게 하면 rules/ 파일의 제목이 매뉴얼에 중복되지 않음
                const lines = fileContent.split('\n');
                let includedContent = fileContent;

                // 첫 번째 줄이 # 으로 시작하면 제거 (선택적)
                // if (lines[0] && lines[0].startsWith('# ')) {
                //     includedContent = lines.slice(1).join('\n');
                // }

                processed = processed.replace(placeholder, includedContent);
                console.log(`✅ Included: ${relativePath}`);
            } else {
                errors.push(`❌ File not found: ${relativePath}`);
                // 파일이 없으면 경고 메시지로 대체
                processed = processed.replace(
                    placeholder,
                    `<!-- ⚠️ INCLUDE ERROR: File not found - ${relativePath} -->`
                );
            }
        } catch (err) {
            errors.push(`❌ Error reading ${relativePath}: ${err.message}`);
            processed = processed.replace(
                placeholder,
                `<!-- ⚠️ INCLUDE ERROR: ${err.message} -->`
            );
        }
    }

    return { content: processed, errors };
}

/**
 * 빌드 타임스탬프 추가
 */
function addBuildTimestamp(content) {
    const timestamp = new Date().toISOString().split('T')[0];
    const buildNote = `<!-- 🔄 Auto-generated from manual_template.md on ${timestamp} -->\n<!-- Do not edit this file directly. Edit manual_template.md instead. -->\n\n`;
    return buildNote + content;
}

/**
 * 메인 빌드 함수
 */
function buildManual() {
    console.log('📖 Building PROJECT_SAL_GRID_MANUAL.md...\n');

    // 템플릿 파일 확인
    if (!fs.existsSync(TEMPLATE_PATH)) {
        console.error('❌ Template file not found:', TEMPLATE_PATH);
        console.log('\n💡 Hint: Create manual_template.md first with INCLUDE placeholders.');
        process.exit(1);
    }

    // 템플릿 읽기
    const template = fs.readFileSync(TEMPLATE_PATH, 'utf-8');

    // INCLUDE 처리
    const { content: processed, errors } = processIncludes(template);

    // 빌드 타임스탬프 추가
    const final = addBuildTimestamp(processed);

    // 결과 저장
    fs.writeFileSync(OUTPUT_PATH, final, 'utf-8');

    console.log(`\n📄 Output: ${OUTPUT_PATH}`);

    // 에러 출력
    if (errors.length > 0) {
        console.log('\n⚠️ Errors/Warnings:');
        errors.forEach(err => console.log(`   ${err}`));
    }

    // 통계
    const includeCount = (template.match(INCLUDE_PATTERN) || []).length;
    console.log(`\n📊 Statistics:`);
    console.log(`   - INCLUDE placeholders processed: ${includeCount}`);
    console.log(`   - Errors: ${errors.length}`);

    console.log('\n✅ Build complete!');
}

// 스크립트 실행
buildManual();
